### ISSUE TITLE
 No rule to make target 'out/host/linux-x86/bin/minigzip', needed by 'out/target/product/m253/ramdisk-recovery.img'

### ISSUE THREAD

**Issue by GuilianoS** [PhantomZone54/twrp_sources_norepo#2]
```bash
guiliano@DESKTOP-VN4JS34:~/twrp$ lunch omni_m253-eng
Traceback (most recent call last):
  File "build/tools/roomservice.py", line 426, in <module>
    os.mkdir(local_manifest_dir)
FileNotFoundError: [Errno 2] No such file or directory: '.repo/local_manifests'

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=16.1.0
TARGET_PRODUCT=omni_m253
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29
HOST_BUILD_TYPE=release
BUILD_ID=MOB31K
OUT_DIR=out
============================================

guiliano@DESKTOP-VN4JS34:~/twrp$ make -j$(nproc --all) recoveryimage
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=16.1.0
TARGET_PRODUCT=omni_m253
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29
HOST_BUILD_TYPE=release
BUILD_ID=MOB31K
OUT_DIR=out
============================================
  File "build/tools/findleaves.py", line 95
    print r
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(r)?
  File "build/tools/findleaves.py", line 95
    print r
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(r)?
  File "build/tools/diff_package_overlays.py", line 88
    print r
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(r)?
No private recovery resources for TARGET_DEVICE m253
build/core/tasks/kernel.mk:104: ***************************************************************
build/core/tasks/kernel.mk:105: * Using prebuilt kernel binary instead of source              *
build/core/tasks/kernel.mk:106: * THIS IS DEPRECATED, AND WILL BE DISCONTINUED                *
build/core/tasks/kernel.mk:107: * Please configure your device to download the kernel         *
build/core/tasks/kernel.mk:108: * source repository to kernel/lge/m253
build/core/tasks/kernel.mk:109: * See http://forum.xda-developers.com/wiki/ROM/Integrated_Kernel_Build
build/core/tasks/kernel.mk:110: * for more information                                        *
build/core/tasks/kernel.mk:111: ***************************************************************
make: *** No rule to make target 'out/host/linux-x86/bin/minigzip', needed by 'out/target/product/m253/ramdisk-recovery.img'.  Stop.

#### make failed to build some targets (1 seconds) ####
```

Note: Format Edited for Visual Ease

**Comment by rokibhasansagar** [comment]
@GuilianoS, please mention the release or tag from which  you downloaded the compressed source.

Note: The files inside the compressed source is not modified by me for android-7.1 to android-9.0, they are same as the __minimal manifest__, just the __roomservice__ is tweaked to start unofficial  build without any __lunch__ error.
Only latest android-5.1 and android-6.0 sources are a little bit updated than the minimal manifest.

**Comment by rokibhasansagar** [comment]
@GuilianoS, by the looks of it, the Device Tree seems to be of Marshmallow platform. But you have `PLATFORM_VERSION=16.1.0` in the `BoradConfig.mk` file, that is required only for android-9.x, so fix the Device Tree too.

**Comment by GuilianoS** [comment]
Thank you!
